// SDL3 Stdinc Bindings
// Standard includes: memory, string, math helpers

// Stdinc functions
extern fn SDL_memset(dst: ?*anyopaque, c: c_int, len: usize) ?*anyopaque;
extern fn SDL_memcpy(dst: ?*anyopaque, src: ?*const anyopaque, len: usize) ?*anyopaque;
extern fn SDL_memmove(dst: ?*anyopaque, src: ?*const anyopaque, len: usize) ?*anyopaque;
extern fn SDL_memcmp(s1: ?*const anyopaque, s2: ?*const anyopaque, len: usize) c_int;
extern fn SDL_strlen(str: ?[*:0]const u8) usize;
extern fn SDL_strlcpy(dst: ?[*:0]u8, src: ?[*:0]const u8, maxlen: usize) usize;
extern fn SDL_utf8strlcpy(dst: ?[*:0]u8, src: ?[*:0]const u8, dst_bytes: usize) usize;
extern fn SDL_strlcat(dst: ?[*:0]u8, src: ?[*:0]const u8, maxlen: usize) usize;
extern fn SDL_strdup(str: ?[*:0]const u8) ?[*:0]u8;
extern fn SDL_strrev(str: ?[*:0]u8) ?[*:0]u8;
extern fn SDL_strupr(str: ?[*:0]u8) ?[*:0]u8;
extern fn SDL_strlwr(str: ?[*:0]u8) ?[*:0]u8;
extern fn SDL_strchr(str: ?[*:0]const u8, c: c_int) ?[*:0]u8;
extern fn SDL_strrchr(str: ?[*:0]const u8, c: c_int) ?[*:0]u8;
extern fn SDL_strstr(haystack: ?[*:0]const u8, needle: ?[*:0]const u8) ?[*:0]u8;
extern fn SDL_strcasestr(haystack: ?[*:0]const u8, needle: ?[*:0]const u8) ?[*:0]u8;
extern fn SDL_strtokr(s1: ?[*:0]u8, s2: ?[*:0]const u8, saveptr: ?*?[*:0]u8) ?[*:0]u8;
extern fn SDL_utf8strlen(str: ?[*:0]const u8) usize;
extern fn SDL_utf8strnlen(str: ?[*:0]const u8, bytes: usize) usize;
extern fn SDL_itoa(value: c_int, str: ?[*:0]u8, radix: c_int) ?[*:0]u8;
extern fn SDL_uitoa(value: c_uint, str: ?[*:0]u8, radix: c_int) ?[*:0]u8;
extern fn SDL_ltoa(value: c_long, str: ?[*:0]u8, radix: c_int) ?[*:0]u8;
extern fn SDL_ultoa(value: c_ulong, str: ?[*:0]u8, radix: c_int) ?[*:0]u8;
extern fn SDL_lltoa(value: i64, str: ?[*:0]u8, radix: c_int) ?[*:0]u8;
extern fn SDL_ulltoa(value: u64, str: ?[*:0]u8, radix: c_int) ?[*:0]u8;
extern fn SDL_atoi(str: ?[*:0]const u8) c_int;
extern fn SDL_atof(str: ?[*:0]const u8) f64;
extern fn SDL_strtol(str: ?[*:0]const u8, endp: ?*?[*:0]u8, base: c_int) c_long;
extern fn SDL_strtoul(str: ?[*:0]const u8, endp: ?*?[*:0]u8, base: c_int) c_ulong;
extern fn SDL_strtoll(str: ?[*:0]const u8, endp: ?*?[*:0]u8, base: c_int) i64;
extern fn SDL_strtoull(str: ?[*:0]const u8, endp: ?*?[*:0]u8, base: c_int) u64;
extern fn SDL_strtod(str: ?[*:0]const u8, endp: ?*?[*:0]u8) f64;
extern fn SDL_abs(x: c_int) c_int;
extern fn SDL_min(x: c_int, y: c_int) c_int;
extern fn SDL_max(x: c_int, y: c_int) c_int;
extern fn SDL_clamp(x: c_int, a: c_int, b: c_int) c_int;
extern fn SDL_isalpha(x: c_int) c_int;
extern fn SDL_isalnum(x: c_int) c_int;
extern fn SDL_isblank(x: c_int) c_int;
extern fn SDL_iscntrl(x: c_int) c_int;
extern fn SDL_isdigit(x: c_int) c_int;
extern fn SDL_isxdigit(x: c_int) c_int;
extern fn SDL_ispunct(x: c_int) c_int;
extern fn SDL_isspace(x: c_int) c_int;
extern fn SDL_isupper(x: c_int) c_int;
extern fn SDL_islower(x: c_int) c_int;
extern fn SDL_isprint(x: c_int) c_int;
extern fn SDL_isgraph(x: c_int) c_int;
extern fn SDL_toupper(x: c_int) c_int;
extern fn SDL_tolower(x: c_int) c_int;

// Public API
pub const memset = SDL_memset;
pub const memcpy = SDL_memcpy;
pub const memmove = SDL_memmove;
pub const memcmp = SDL_memcmp;
pub const strlen = SDL_strlen;
pub const strlcpy = SDL_strlcpy;
pub const utf8strlcpy = SDL_utf8strlcpy;
pub const strlcat = SDL_strlcat;
pub const strdup = SDL_strdup;
pub const strrev = SDL_strrev;
pub const strupr = SDL_strupr;
pub const strlwr = SDL_strlwr;
pub const strchr = SDL_strchr;
pub const strrchr = SDL_strrchr;
pub const strstr = SDL_strstr;
pub const strcasestr = SDL_strcasestr;
pub const strtokr = SDL_strtokr;
pub const utf8strlen = SDL_utf8strlen;
pub const utf8strnlen = SDL_utf8strnlen;
pub const itoa = SDL_itoa;
pub const uitoa = SDL_uitoa;
pub const ltoa = SDL_ltoa;
pub const ultoa = SDL_ultoa;
pub const lltoa = SDL_lltoa;
pub const ulltoa = SDL_ulltoa;
pub const atoi = SDL_atoi;
pub const atof = SDL_atof;
pub const strtol = SDL_strtol;
pub const strtoul = SDL_strtoul;
pub const strtoll = SDL_strtoll;
pub const strtoull = SDL_strtoull;
pub const strtod = SDL_strtod;
pub const abs = SDL_abs;
pub const min = SDL_min;
pub const max = SDL_max;
pub const clamp = SDL_clamp;
pub const isalpha = SDL_isalpha;
pub const isalnum = SDL_isalnum;
pub const isblank = SDL_isblank;
pub const iscntrl = SDL_iscntrl;
pub const isdigit = SDL_isdigit;
pub const isxdigit = SDL_isxdigit;
pub const ispunct = SDL_ispunct;
pub const isspace = SDL_isspace;
pub const isupper = SDL_isupper;
pub const islower = SDL_islower;
pub const isprint = SDL_isprint;
pub const isgraph = SDL_isgraph;
pub const toupper = SDL_toupper;
pub const tolower = SDL_tolower;
